dmhy_rss_spider:
  name:
    - 女神異聞錄5
    - 齐木楠雄的灾难
    - 魔卡少女樱透明卡篇
    - 全金属狂潮4
    - 七大罪戒律的复活
    - 奴隶区
    - 銀河英雄傳說
    - 海贼王
    - 黃金神威
    - 黑色五叶草
    - MEGALO_BOX
    - SteinsGate0
  re:
    - .+極影字幕社.+女神異聞錄5.+\d{1,}.+BIG5.+720P.+MP4
    - .+豌豆字幕组.+风之圣殿字幕组.+齐木楠雄的灾难.+第二季.+\d{1,}.+简体.+720P.+MP4
    - .+(?=.*豌豆字幕組&風之聖殿字幕組)(?=.*魔卡少女櫻)(?=.*繁體)(?=.*720P)(?=.*MP4)
    - .+雪飘工作室.+全金属狂潮.+\d{1,}.+720p.+简体内嵌
    - .+(?=.*豌豆字幕组)(?=.*七大罪)(?=.*BIG5繁體)(?=.*720P)
    - .+(?=.*西農YUI漢化組)(?=.*奴隸區The)(?=.*BIG5繁體)(?=.*720P)
    - .+漫遊字幕組&澄空學園&天香字幕社.+銀河英雄傳說.+Die.+Neue.+These.+\d{1,}.+繁體內嵌.+720P.+MP4
    - .+(?=.*OPFans枫雪动漫)(?=.*海贼王)(?=.*720P)(?=.*周日版)
    - .+(?=.*幻櫻字幕組)(?=.*黃金神威)(?=.*BIG5_MP4)(?=.*1280X720)
    - .+(?=.*DMHY)(?=.*黑色五葉草)(?=.*繁體)(?=.*720P)(?=.*MP4)
    - .+(?=.*四月新番)(?=.*MEGALO BOX)(?=.*GB_MP4)(?=.*1920×1080)
    - .+(?=.*澄空學園&雪飄工作室&華盟字幕社)(?=.*Steins;Gate 0)(?=.*720p)(?=.*繁體內嵌)