dmhy_rss_spider:
  name:
    - 女神異聞錄5
    - 海贼王
    - 黑色五叶草
    - SteinsGate0
    - 我的英雄学院3
    - 工作细胞
    - 银魂
    - 进击的巨人3
    - 妖怪旅馆营业中
    - 百炼霸王与圣约女武神
    - overload3
    - 摇曳庄幽奈小姐
    - 碧蓝之海
    - 七星团
    - 后街女孩
    - 杀戮天使
    - 异世界魔王与召唤少女魔术
  re:
    - .+極影字幕社.+女神異聞錄5.+\d{1,}.+BIG5.+720P.+MP4
    - .+(?=.Skytree)(?=.*海贼王)(?=.*X264)(?=.*720P)(?=.*GB_JP)(?=.*MP4)
    - .+(?=.*DMHY)(?=.*黑色五葉草)(?=.*繁體)(?=.*720P)(?=.*MP4)
    - .+(?=.*澄空學園&雪飄工作室&華盟字幕社)(?=.*Steins;Gate 0)(?=.*720p)(?=.*繁體內嵌)
    - .+(?=.*八重櫻字幕組)(?=.*我的英雄學院S3)(?=.*繁体)(?=.*720P)
    - .+(?=.*喵萌奶茶屋)(?=.*工作細胞)(?=.*720p)(?=.*繁體)
    - .+(?=.*LAC字幕組)(?=.*銀魂)(?=.*720P_繁中)
    - .+(?=.*極影字幕社)(?=.*進擊的巨人 3)(?=.*BIG5)(?=.*MP4_720P)
    - .+(?=.*搬运)(?=.*妖怪旅馆营业中)(?=.*1080p)(?=.*中文&日文字幕)
    - .+(?=.*澄空&雪飄)(?=.*百煉霸王與聖約女武神)(?=.*720p)(?=.*繁體內嵌)
    - .+(?=.*八重櫻字幕組)(?=.*Overlord III)(?=.*720p)(?=.*繁體)
    - .+(?=.*動漫國字幕組)(?=.*搖曳莊的幽奈小姐)(?=.*720p)(?=.*繁體)
    - .+(?=.*悠哈璃羽字幕社＆西農YUI漢化組)(?=.*Grand Blue)(?=.*x264 720p)(?=.*CHT)
    - .+(?=.*波洛咖啡廳Reunion攻略組)(?=.*七星之昴星團)(?=.*繁日雙語字幕)(?=.*1080P)
    - .+(?=.*極影字幕社)(?=.*後街女孩)(?=.*BIG5)(?=.*720P)
    - .+(?=.*極影字幕社)(?=.*殺戮的天使)(?=.*BIG5)(?=.*MP4_720)
    - .+(?=.*c.c动漫)(?=.*异世界魔王与召唤少女的奴隶魔术)(?=.*GB)(?=.*1080P)           